sensors:
  - default_sensor
  - kinect_depthimage
default_sensor:
  filtered_cloud_topic: pcl_topic
  max_range: 10.0
  max_update_rate: 10.0
  padding_offset: 10.0
  padding_scale: 10.0
  point_cloud_topic: pcl_topic
  point_subsample: 10
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
kinect_depthimage:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /head_mount_kinect/depth_registered/image_raw
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2